---
version: "3"

services:
    meilisearch:
        image: getmeili/meilisearch:v0.30.5
        ports:
            - "7700:7700"
        environment:
            - http_proxy
            - https_proxy
            - MEILI_MASTER_KEY=masterKey
            - MEILI_NO_ANALYTICS=true
            - MEILI_ENV=development
            - MEILI_LOG_LEVEL
            - MEILI_DB_PATH=/data.ms
        volumes:
            - ms_data:/data.ms

volumes:
    ms_data:
        driver: local
